### ISSUE TITLE
Bug Menu de pause

### ISSUE THREAD

**Issue by Kevin-Bannier** [ESIR2-IN-promo2017/SI-TP-fun#3]
Le menu de pause ne fonctionne pas correctement. Lorsque l'on appuie sur ECHAP, la pop-up s'affiche correctement. Mais à ce moment là :
- si on clique sur ok, la pop-up réapparaît
- si on appuie sur ECHAP, la pop-up réapparaît

**Comment by Karkariy** [comment]
Vérifie car moi sa me ne le fait pas. je viens de repush

**Comment by Kevin-Bannier** [comment]
C'est pareil.
Quand j'appuie (la 1ère fois) sur ECHAP, ça affiche "echap" dans la console. Et quand j'appuie sur ok, ça ré-affiche "echap" dans la console.
